### ISSUE TITLE
Why is there no ground truth for the data downloaded by STexampleData?

### ISSUE THREAD

**Issue by hucongcong97** [lmweber/STexampleData#3]
STexampleData claims to contain 5 data, which are
![image](https://github.com/lmweber/STexampleData/assets/82995677/b202bbd5-c44e-434e-a7c1-bf7bde339107)
But when I successfully installed the STexampleData package, I found only three data：
![image](https://github.com/lmweber/STexampleData/assets/82995677/f09b2b99-f74c-49ef-8e43-334bd5a4264a)
What is even more puzzling is that after loading the data, I found that there is no gold standard for each data, which undoubtedly delays the use of data
![image](https://github.com/lmweber/STexampleData/assets/82995677/8f697838-6f6b-499f-a26e-01be011239bd)
Could you please provide a link to the gold standard data? thank you very much

**Comment by lmweber** [comment]
Hi, several of the datasets contain reference annotation labels or ground truth labels provided by the authors of the original studies. These labels are included as columns in the `colData` of those datasets, as described in the documentation.

For more details, please see the documentation, either the help files or the tutorial available on the Bioconductor website (direct link [here](https://bioconductor.org/packages/release/data/experiment/vignettes/STexampleData/inst/doc/STexampleData_overview.html)).

There is also a typo in your code for loading the dataset above (you have included an extra space before the dataset name), which is why it is returning an error. Thank you.
